remote_theme: pmarsceill/just-the-docs
title: Ebook Generator Documentation
description: Documentation for the AI-powered Ebook Generator system
baseurl: "/ebook-generator" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Aux links for the upper right navigation
aux_links:
  "Ebook Generator on GitHub":
    - "//github.com/mosadd1X/ebook-generator"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Color scheme
color_scheme: light

# Footer content
footer_content: "Copyright &copy; 2023-2024. Distributed under the MIT license."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/mosadd1X/ebook-generator"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
gh_edit_source: docs

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
